//#header
MODULE ExportItems;

REQUIRE StockItem;
//#header end
run() {
    EXPORT FROM item = upper(name(Item i)), currentBalance(i, Stock s), 
    			stock = name(s), barcode(i), salePrice(i)
        	WHERE (name(i) LIKE '%а%' OR salePrice(i) > 10) 
        		AND currentBalance(i, s); // по умолчанию записывает результат в exportFile, а свойства export* являются результатами HTTP запроса по умолчанию
}
