//#header
MODULE ExportItems;

REQUIRE StockItem;
//#header end
run() {
    EXPORT FROM item = upper(name(Item i)), currentBalance(i, Stock s), 
    			stock = name(s), barcode(i), salePrice(i)
        	WHERE (name(i) LIKE '%а%' OR salePrice(i) > 10) 
        		AND currentBalance(i, s); // by default writes the result to exportFile, and export* properties are the default results of the HTTP request
}
