MODULE MetaSampleResult;

FORM documentForm;
FORM orderForm;
showMessage  { };
closeForm  { };

CLASS Document;
CLASS Type;

EXTEND FORM documentForm
    PROPERTIES() showMessage, closeForm
;
  
EXTEND FORM orderForm
    PROPERTIES() showMessage, closeForm
;

DocumentName 'Document name' = DATA BPSTRING[100](Document);
DocumentType 'Document type' = DATA Type (Document);
DocumentValue 'Document cost' = DATA INTEGER (Document);
