MODULE ResolveB;

REQUIRE ResolveA;

f = DATA INTEGER (B);

h(C c) = f(c); // найдет верхнее объявление - ResolveB.f[B]
j(C c) = ResolveA.f(c); // найдет объявление в ResolveA - ResolveA.f[C]
z(C c) = f[A](c); // найдет объявление в ResolveA - ResolveA.f[A]

test(C c, A a) {
    LOCAL f = INTEGER (B);
    
    f(c) <- 1; // найдет верхнее объявление - f[B]
    MESSAGE f(a); // найдет верхнее объявление - f[B]
    ResolveB.f(c) <- 1; // найдет верхнее объявление в ResolveB - ResolveB.f[B]
}
