MODULE StaticObjectSample;

CLASS Direction 'Direction'
{
    north 'North',
    east 'East',
    south 'South',
    west 'West'   
}
  
direction = DATA Direction ();
  
showDirection  { 
    MESSAGE staticName(direction());
    MESSAGE staticCaption(direction());
}
  
// creating a form by choosing an object of Direction class
FORM directions 'Directions'
    OBJECTS d = Direction
    PROPERTIES(d) READONLY staticCaption
    
    LIST Direction OBJECT d
; 