MODULE UseCaseDBModel;

CLASS Animal 'Animal';
TABLE animal(Animal);

name 'Name' = DATA STRING[50] (Animal);

CLASS Country 'Country';

TABLE animalCountry (Animal, Country);
population 'Number' = DATA INTEGER (Animal, Country);

TABLE ageAnimalCountry (Animal, Country);
averageAge 'Average age' = DATA NUMERIC[8,2] (Animal, Country) TABLE ageAnimalCountry;

totalPopulation 'Total number' (Animal a) = GROUP SUM population(a, Country c) MATERIALIZED;
