MODULE UseCaseNameTest2;

REQUIRE UseCaseNamePurchase, UseCaseNameSale;

//#priority
PRIORITY Purchase;
//#priority end

//#namespace
NAMESPACE Purchase;
//#namespace end

//#sample
messagePurchaseCount 'Display the number of purchase orders' {
    MESSAGE GROUP SUM 1 IF o IS Order;
}
messageSaleCount 'Display the number of sales orders' {
    MESSAGE GROUP SUM 1 IF o IS Sale.Order;
}

NAVIGATOR {
    NEW ACTION messagePurchaseCount;
    NEW ACTION messageSaleCount;
}
//#sample end