MODULE UseCaseNameTest2;

REQUIRE UseCaseNamePurchase, UseCaseNameSale;

//#priority
PRIORITY Purchase;
//#priority end

//#namespace
NAMESPACE Purchase;
//#namespace end

//#sample
messagePurchaseCount 'Вывести кол-во заказов на закупку' {
    MESSAGE GROUP SUM 1 IF o IS Order;
}
messageSaleCount 'Вывести кол-во заказов на продажу' {
    MESSAGE GROUP SUM 1 IF o IS Sale.Order;
}

NAVIGATOR {
    NEW ACTION messagePurchaseCount;
    NEW ACTION messageSaleCount;
}
//#sample end