MODULE UseCaseNavigator;

//#sample1
FORM categories 'Categories';
FORM books 'Books';
//#sample1 end

//#solution1
NAVIGATOR {
    NEW FOLDER application 'Application' WINDOW toolbar FIRST {
        NEW categories;
        NEW books;
    }
}
//#solution1 end

//#solution2
NAVIGATOR {
    application {
        NEW FOLDER masterData 'Directories' {
            NEW categories;
            NEW books;
        }
    }
}
//#solution2 end