MODULE UseCaseNameTest2;

//#sample
REQUIRE UseCaseNamePurchase, UseCaseNameSale;

NAMESPACE Purchase;

messagePurchaseCount 'Вывести кол-во заказов на закупку' {
    MESSAGE GROUP SUM 1 IF o IS Order;
}
messageSaleCount 'Вывести кол-во заказов на продажу' {
    MESSAGE GROUP SUM 1 IF o IS Sale.Order;
}

NAVIGATOR {
    NEW ACTION messagePurchaseCount;
    NEW ACTION messageSaleCount;
}
//#sample end