//#header
//#module
MODULE Item;
//#module end
//#header end

//#class
CLASS Item 'Product';

name 'Name' = DATA STRING[100](Item) IN base;
barcode 'Barcode' = DATA BPSTRING[13](Item) IN base;
//#class end

//#price
salePrice 'Wholesale price' = DATA NUMERIC[17,2](Item) IN base;
//#price end

//#form
FORM items 'Products'
	OBJECTS i = Item
	PROPERTIES(i) name, barcode, salePrice, NEW, DELETE
;
//#form end