MODULE LegalEntity;

CLASS LegalEntity 'Organization';

name 'Name' = DATA STRING[100](LegalEntity) IN base;
address 'Address' = DATA STRING[150](LegalEntity) IN base;
inn 'TIN' = DATA BPSTRING[9](LegalEntity) IN base;

legalEntityINN = GROUP AGGR LegalEntity legalEntity BY inn(legalEntity);

FORM legalEntities 'Organization'
	OBJECTS l = LegalEntity
	PROPERTIES(l) name, inn, address, NEW, DELETE
;
